import { join, dirname } from "node:path";
import {
  existsSync,
  readFileSync,
  writeFileSync,
  mkdirSync,
  cpSync,
  readdirSync,
} from "node:fs";
import {
  STAGING_DIR_NAME,
  MANIFEST_FILE,
  SKILLS_DIR,
  INSTRUCTIONS_DIR,
  TEMPLATES_DIR,
} from "./constants.mjs";
import { buildManifest } from "./plan.mjs";

/**
 * Generation module — writes artifacts to the staging directory.
 */

// ─── YAML Formatter ─────────────────────────────────────────────────────────

export function formatYaml(obj, indent = 0) {
  const pad = " ".repeat(indent);
  let out = "";

  for (const [key, value] of Object.entries(obj)) {
    if (value === null || value === undefined) continue;

    if (Array.isArray(value)) {
      if (value.length === 0) {
        out += `${pad}${key}: []\n`;
      } else if (typeof value[0] === "object") {
        out += `${pad}${key}:\n`;
        for (const item of value) {
          const lines = formatYaml(item, indent + 4)
            .split("\n")
            .filter(Boolean);
          out += `${pad}  - ${lines[0].trim()}\n`;
          for (const line of lines.slice(1)) {
            out += `${pad}    ${line.trim()}\n`;
          }
        }
      } else {
        out += `${pad}${key}:\n`;
        for (const item of value) {
          out += `${pad}  - ${item.includes(" ") || item.includes("*") ? `"${item}"` : item}\n`;
        }
      }
    } else if (typeof value === "object") {
      out += `${pad}${key}:\n`;
      out += formatYaml(value, indent + 2);
    } else if (typeof value === "string" && (value.includes(" ") || value.includes("<"))) {
      out += `${pad}${key}: "${value}"\n`;
    } else {
      out += `${pad}${key}: ${value}\n`;
    }
  }

  return out;
}

// ─── File Generators ────────────────────────────────────────────────────────

export function generateProfileYaml(profile) {
  return (
    `# Repository Profile\n` +
    `# yaml-language-server: $schema=https://raw.githubusercontent.com/eduardohilariodev/copilot-quickstart/main/schemas/repo-profile.schema.json\n` +
    `# Generated by copilot-quickstart v2.0.0\n` +
    `# Review and fill in <placeholders> before running meta-skills\n\n` +
    formatYaml(profile)
  );
}

export function generateAgentsMd(profile) {
  const name = profile.name || "this-repo";
  const langs = profile.languages?.join(", ") || "not specified";
  const frameworks = profile.frameworks?.join(", ") || "none";
  const arch = profile.architecture || "monolith";
  const cmds = profile.build_commands || {};

  let md = `# AGENTS.md — ${name}\n\n`;
  md += `## Quick Reference\n\n`;
  md += `| Key | Value |\n|-----|-------|\n`;
  md += `| Languages | ${langs} |\n`;
  md += `| Frameworks | ${frameworks} |\n`;
  md += `| Architecture | ${arch} |\n`;
  md += `| Risk Level | ${profile.risk_level || "medium"} |\n\n`;

  md += `## Commands\n\n`;
  md += `| Action | Command |\n|--------|--------|\n`;
  if (cmds.install) md += `| Install | \`${cmds.install}\` |\n`;
  if (cmds.build) md += `| Build | \`${cmds.build}\` |\n`;
  if (cmds.test) md += `| Test | \`${cmds.test}\` |\n`;
  if (cmds.lint) md += `| Lint | \`${cmds.lint}\` |\n`;
  if (cmds.dev) md += `| Dev | \`${cmds.dev}\` |\n`;
  md += `\n`;

  md += `## Architecture\n\n`;
  md += `<!-- Fill in: describe key modules, boundaries, and data flow -->\n\n`;

  md += `## Code Conventions\n\n`;
  md += `- Follow existing patterns in the codebase\n`;
  md += `- ${profile.conventions?.naming || "Use consistent naming conventions"}\n`;
  md += `- ${profile.conventions?.testing_strategy || "Write tests for new features"}\n\n`;

  md += `## Protected Paths\n\n`;
  md += `Do NOT modify these without explicit approval:\n`;
  md += (profile.protected_paths || [".env*"]).map((p) => `- \`${p}\``).join("\n");
  md += `\n\n`;

  md += `## Agent Guidelines\n\n`;
  md += `- Read this file before making changes\n`;
  md += `- Run tests after every modification\n`;
  md += `- Keep commits small and focused\n`;
  md += `- Ask before architectural changes\n\n`;

  md += `## AI Maintenance\n\n`;
  md += `Run periodically to keep AI config healthy:\n`;
  md += `- Weekly: \`health-dashboard\`\n`;
  md += `- Monthly: \`audit-skills\`, \`detect-drift\`\n`;
  md += `- Quarterly: \`prune-skills\`, \`check-compatibility\`\n`;

  return md;
}

export function generateInstructions(profile) {
  const langs = profile.languages?.join(", ") || "this project";
  const frameworks = profile.frameworks?.join(", ");

  let md = `# Copilot Instructions\n\n`;
  md += `## Project Context\n\n`;
  md += `This is a ${profile.architecture || "monolith"} project using ${langs}${frameworks ? ` with ${frameworks}` : ""}.\n\n`;

  md += `## Code Style\n\n`;
  md += `- Follow existing patterns in the codebase\n`;
  md += `- ${profile.conventions?.naming || "Use consistent naming conventions"}\n`;
  md += `- Write clear, self-documenting code\n\n`;

  md += `## Testing\n\n`;
  md += `- ${profile.conventions?.testing_strategy || "Write tests for new features and bug fixes"}\n`;
  if (profile.build_commands?.test) {
    md += `- Run tests: \`${profile.build_commands.test}\`\n`;
  }
  md += `\n`;

  md += `## Safety\n\n`;
  md += `- Never modify files matching: ${(profile.protected_paths || [".env*"]).join(", ")}\n`;
  md += `- Never commit secrets or credentials\n`;
  md += `- Always verify changes compile/pass before committing\n\n`;

  md += `## When Unsure\n\n`;
  md += `- Check AGENTS.md for architecture guidance\n`;
  md += `- Look at existing similar code for patterns\n`;
  md += `- Ask the developer rather than guessing\n`;

  return md;
}

export function generateVscodeSettings() {
  return JSON.stringify(
    {
      "chat.instructionsFilesLocations": {
        ".github/instructions/**/*.instructions.md": true,
      },
    },
    null,
    2
  ) + "\n";
}

// ─── Staging Orchestrator ───────────────────────────────────────────────────

/**
 * Write all planned artifacts to the staging directory.
 * @returns {{ written: string[], skipped: string[] }}
 */
export function stageArtifacts(target, artifacts, profile, scan) {
  const stagingDir = join(target, STAGING_DIR_NAME);
  const written = [];
  const skipped = [];

  for (const artifact of artifacts) {
    if (artifact.action === "skip") {
      skipped.push(artifact.label);
      continue;
    }

    const destPath = join(stagingDir, artifact.stagePath);

    // Ensure directory exists
    mkdirSync(dirname(destPath), { recursive: true });

    // Generate content based on artifact type
    switch (artifact.id) {
      case "repo-profile":
        writeFileSync(destPath, generateProfileYaml(profile), "utf8");
        break;

      case "agents-md":
        writeFileSync(destPath, generateAgentsMd(profile), "utf8");
        break;

      case "copilot-instructions":
        writeFileSync(destPath, generateInstructions(profile), "utf8");
        break;

      case "vscode-settings":
        writeFileSync(destPath, generateVscodeSettings(), "utf8");
        break;

      case "starter-skills":
        stageSkills(destPath);
        break;

      default:
        // Path-specific instruction templates
        if (artifact.templateSource) {
          stageInstructionTemplate(destPath, artifact.templateSource);
        }
        break;
    }

    written.push(artifact.label);
  }

  // Write manifest
  const manifest = buildManifest(artifacts, profile, scan);
  writeFileSync(
    join(stagingDir, MANIFEST_FILE),
    JSON.stringify(manifest, null, 2) + "\n",
    "utf8"
  );

  return { written, skipped };
}

function stageSkills(destDir) {
  if (!existsSync(SKILLS_DIR)) return;

  const skillDirs = readdirSync(SKILLS_DIR, { withFileTypes: true }).filter(
    (d) => d.isDirectory()
  );

  for (const dir of skillDirs) {
    const src = join(SKILLS_DIR, dir.name, "SKILL.md");
    if (existsSync(src)) {
      const dest = join(destDir, dir.name);
      mkdirSync(dest, { recursive: true });
      cpSync(src, join(dest, "SKILL.md"));
    }
  }
}

function stageInstructionTemplate(destPath, templateFile) {
  const src = join(INSTRUCTIONS_DIR, templateFile);
  if (existsSync(src)) {
    cpSync(src, destPath);
  }
}

// ─── Apply (move staged → final) ───────────────────────────────────────────

/**
 * Read the staging manifest and apply files.
 * @returns {{ applied: string[], skipped: string[], errors: string[] }}
 */
export function applyStaged(target, force = false) {
  const stagingDir = join(target, STAGING_DIR_NAME);
  const manifestPath = join(stagingDir, MANIFEST_FILE);

  if (!existsSync(stagingDir)) {
    return { applied: [], skipped: [], errors: ["No ai-setup/ directory found. Run onboard first."] };
  }

  // Read manifest
  let manifest = null;
  if (existsSync(manifestPath)) {
    try {
      manifest = JSON.parse(readFileSync(manifestPath, "utf8"));
    } catch {}
  }

  if (!manifest) {
    return { applied: [], skipped: [], errors: ["No valid manifest found. Re-run onboard to regenerate."] };
  }

  const applied = [];
  const skipped = [];
  const errors = [];

  for (const artifact of manifest.artifacts) {
    const src = join(stagingDir, artifact.stagePath);
    const dest = join(target, artifact.targetPath);

    if (!existsSync(src)) {
      // For directory artifacts, check if directory exists
      if (artifact.id === "starter-skills") {
        const skillsSrc = join(stagingDir, ".github", "skills");
        if (existsSync(skillsSrc)) {
          const skillsDest = join(target, ".github", "skills");
          mkdirSync(skillsDest, { recursive: true });
          cpSync(skillsSrc, skillsDest, { recursive: true, force });
          applied.push(artifact.targetPath);
        }
      }
      continue;
    }

    if (existsSync(dest) && !force) {
      skipped.push(`${artifact.targetPath} (exists, use --force)`);
      continue;
    }

    try {
      mkdirSync(dirname(dest), { recursive: true });
      cpSync(src, dest);
      applied.push(artifact.targetPath);
    } catch (err) {
      errors.push(`${artifact.targetPath}: ${err.message}`);
    }
  }

  return { applied, skipped, errors };
}
