import { join, dirname } from "node:path";
import {
  existsSync,
  readFileSync,
  writeFileSync,
  mkdirSync,
  cpSync,
  readdirSync,
} from "node:fs";
import {
  STAGING_DIR_NAME,
  MANIFEST_FILE,
  SKILLS_DIR,
  AGENTS_DIR,
  INSTRUCTIONS_DIR,
  TEMPLATES_DIR,
  META_SKILLS_DIR,
  MAINTENANCE_SKILLS,
} from "./constants.mjs";
import { buildManifest } from "./plan.mjs";

/**
 * Generation module — writes artifacts to the staging directory.
 */

// ─── YAML Formatter ─────────────────────────────────────────────────────────

export function formatYaml(obj, indent = 0) {
  const pad = " ".repeat(indent);
  let out = "";

  for (const [key, value] of Object.entries(obj)) {
    if (value === null || value === undefined) continue;

    if (Array.isArray(value)) {
      if (value.length === 0) {
        out += `${pad}${key}: []\n`;
      } else if (typeof value[0] === "object") {
        out += `${pad}${key}:\n`;
        for (const item of value) {
          const lines = formatYaml(item, indent + 4)
            .split("\n")
            .filter(Boolean);
          out += `${pad}  - ${lines[0].trim()}\n`;
          for (const line of lines.slice(1)) {
            out += `${pad}    ${line.trim()}\n`;
          }
        }
      } else {
        out += `${pad}${key}:\n`;
        for (const item of value) {
          out += `${pad}  - ${item.includes(" ") || item.includes("*") ? `"${item}"` : item}\n`;
        }
      }
    } else if (typeof value === "object") {
      out += `${pad}${key}:\n`;
      out += formatYaml(value, indent + 2);
    } else if (typeof value === "string" && (value.includes(" ") || value.includes("<"))) {
      out += `${pad}${key}: "${value}"\n`;
    } else {
      out += `${pad}${key}: ${value}\n`;
    }
  }

  return out;
}

// ─── File Generators ────────────────────────────────────────────────────────

export function generateProfileYaml(profile) {
  return (
    `# Repository Profile\n` +
    `# yaml-language-server: $schema=https://raw.githubusercontent.com/eduardohilariodev/copilot-quickstart/main/schemas/repo-profile.schema.json\n` +
    `# Generated by copilot-quickstart v2.0.0\n` +
    `# Review and fill in <placeholders> before running meta-skills\n\n` +
    formatYaml(profile)
  );
}

export function generateAgentsMd(profile) {
  const name = profile.name || "this-repo";
  const langs = profile.languages?.join(", ") || "not specified";
  const frameworks = profile.frameworks?.join(", ") || "none";
  const arch = profile.architecture || "monolith";
  const cmds = profile.build_commands || {};

  const templatePath = join(TEMPLATES_DIR, "AGENTS.md");
  if (existsSync(templatePath)) {
    let content = readFileSync(templatePath, "utf8");

    // Replace known placeholders with actual profile data
    content = content
      .replace("{{repo_name}}", name)
      .replace("{{project_description}}", `<!-- TODO: Add project description -->`)
      .replace("{{architecture_type}}", arch)
      .replace("{{languages}}", langs)
      .replace("{{frameworks}}", frameworks)
      .replace("{{directory_tree}}", `<!-- Run: tree -L 2 -I node_modules to fill -->`)
      .replace("{{cmd_install}}", cmds.install || "npm install")
      .replace("{{cmd_build}}", cmds.build || "npm run build")
      .replace("{{cmd_test}}", cmds.test || "npm test")
      .replace("{{cmd_lint}}", cmds.lint || "npm run lint")
      .replace("{{cmd_format}}", cmds.format || "npx prettier --write .")
      .replace("{{naming_conventions}}", buildNamingSection(profile))
      .replace("{{code_organization_rules}}", "- Follow existing patterns in the codebase\n- Use consistent naming (Copilot infers these from existing code)")
      .replace("{{error_handling_pattern}}", "- Follow existing error handling patterns\n- Add context to error messages")
      .replace("{{testing_strategy}}", cmds.test ? `- Run tests: \`${cmds.test}\`\n- Write tests for new features` : "- Write tests for new features and bug fixes")
      .replace("{{decision_1_title}}", "Decision 1")
      .replace("{{decision_1_rationale}}", "<!-- Document non-obvious architectural decisions here -->")
      .replace("{{decision_2_title}}", "Decision 2")
      .replace("{{decision_2_rationale}}", "<!-- Add more decisions as needed -->")
      .replace("{{protected_paths_list}}", (profile.protected_paths || [".env*", "*.secret"]).map((p) => `- \`${p}\``).join("\n"))
      .replace("{{runtime}}", detectRuntime(profile))
      .replace("{{package_manager}}", detectPackageManager(profile))
      .replace("{{ci_cd_platform}}", "<!-- Fill: GitHub Actions, GitLab CI, etc. -->");

    return content;
  }

  // Fallback: inline generation (original behavior)
  return generateAgentsMdFallback(profile);
}

function buildNamingSection(profile) {
  if (!profile.naming) {
    return "- AI artifacts follow `kebab-case` naming\n- Skills: `verb-noun` (e.g., `test-generator`)\n- Agents: `role-scope` (e.g., `coding-refactor`)";
  }

  let section = "";
  if (profile.naming.skills_pattern === "verb-ing-domain") {
    section += "- Skills: `verb-ing-domain` (e.g., `testing-code`, `managing-branches`)\n";
  } else {
    section += "- Skills: `domain-verb` (e.g., `code-testing`, `branch-managing`)\n";
  }
  if (profile.naming.agents_pattern === "role-scope") {
    section += "- Agents: `role-scope` (e.g., `coding-refactor`, `pr-code-review`)\n";
  } else {
    section += "- Agents: `domain-role` (e.g., `frontend-review`, `backend-coding`)\n";
  }
  if (profile.naming.instructions_pattern === "topic") {
    section += "- Instructions: `<topic>.instructions.md` (e.g., `frontend.instructions.md`)";
  } else {
    section += "- Instructions: `<tech-domain-focus>.instructions.md` (e.g., `react-best-practices.instructions.md`)";
  }
  return section;
}

function detectRuntime(profile) {
  if (profile.languages?.includes("typescript") || profile.languages?.includes("javascript")) return "Node.js";
  if (profile.languages?.includes("python")) return "Python";
  if (profile.languages?.includes("go")) return "Go";
  if (profile.languages?.includes("rust")) return "Rust";
  if (profile.languages?.includes("java")) return "Java / JVM";
  return "<!-- Specify runtime -->";
}

function detectPackageManager(profile) {
  const install = profile.build_commands?.install || "";
  if (install.includes("pnpm")) return "pnpm";
  if (install.includes("yarn")) return "yarn";
  if (install.includes("bun")) return "bun";
  if (install.includes("npm")) return "npm";
  if (install.includes("pip")) return "pip";
  if (install.includes("cargo")) return "cargo";
  return "<!-- Specify package manager -->";
}

function generateAgentsMdFallback(profile) {
  const name = profile.name || "this-repo";
  const langs = profile.languages?.join(", ") || "not specified";
  const frameworks = profile.frameworks?.join(", ") || "none";
  const arch = profile.architecture || "monolith";
  const cmds = profile.build_commands || {};

  let md = `# AGENTS.md — ${name}\n\n`;
  md += `## Quick Reference\n\n`;
  md += `| Key | Value |\n|-----|-------|\n`;
  md += `| Languages | ${langs} |\n`;
  md += `| Frameworks | ${frameworks} |\n`;
  md += `| Architecture | ${arch} |\n`;
  md += `| Risk Level | ${profile.risk_level || "medium"} |\n\n`;

  md += `## Commands\n\n`;
  md += `| Action | Command |\n|--------|--------|\n`;
  if (cmds.install) md += `| Install | \`${cmds.install}\` |\n`;
  if (cmds.build) md += `| Build | \`${cmds.build}\` |\n`;
  if (cmds.test) md += `| Test | \`${cmds.test}\` |\n`;
  if (cmds.lint) md += `| Lint | \`${cmds.lint}\` |\n`;
  if (cmds.dev) md += `| Dev | \`${cmds.dev}\` |\n`;
  md += `\n`;

  md += `## Architecture\n\n`;
  md += `<!-- Fill in: describe key modules, boundaries, and data flow -->\n\n`;

  md += `## Code Conventions\n\n`;
  md += `- Follow existing patterns in the codebase\n`;
  md += `- Use consistent naming conventions (Copilot infers these from existing code)\n`;
  md += `- Write tests for new features\n\n`;

  md += `## Protected Paths\n\n`;
  md += `Do NOT modify these without explicit approval:\n`;
  md += (profile.protected_paths || [".env*"]).map((p) => `- \`${p}\``).join("\n");
  md += `\n\n`;

  md += `## Agent Guidelines\n\n`;
  md += `- Read this file before making changes\n`;
  md += `- Run tests after every modification\n`;
  md += `- Keep commits small and focused\n`;
  md += `- Ask before architectural changes\n`;

  return md;
}

export function generateInstructions(profile) {
  const langs = profile.languages?.join(", ") || "this project";
  const frameworks = profile.frameworks?.join(", ");
  const arch = profile.architecture || "monolith";

  const templatePath = join(TEMPLATES_DIR, "copilot-instructions.md");
  if (existsSync(templatePath)) {
    let content = readFileSync(templatePath, "utf8");

    content = content
      .replace("{{repo_name}}", profile.name || "this-repo")
      .replace("{{architecture_type}}", arch)
      .replace("{{languages}}", langs)
      .replace("{{frameworks_clause}}", frameworks ? `with ${frameworks}` : "")
      .replace("{{code_style_rules}}", "- Follow existing patterns in the codebase\n- Use consistent naming conventions (Copilot infers these from existing code)\n- Write clear, self-documenting code")
      .replace("{{testing_rules}}", profile.build_commands?.test
        ? `- Write tests for new features and bug fixes\n- Run tests: \`${profile.build_commands.test}\``
        : "- Write tests for new features and bug fixes")
      .replace("{{git_workflow_rules}}", "- Keep commits small and focused\n- Write descriptive commit messages\n- Create feature branches for changes")
      .replace("{{architecture_rules}}", "- Respect module boundaries\n- Keep dependencies flowing in one direction\n- Ask before making architectural changes")
      .replace("{{protected_paths}}", (profile.protected_paths || [".env*"]).join(", "))
      .replace("{{additional_security_rules}}", "")
      .replace("{{documentation_rules}}", "- Update docs when behavior changes\n- Document non-obvious decisions inline");

    return content;
  }

  // Fallback: inline generation
  return generateInstructionsFallback(profile);
}

function generateInstructionsFallback(profile) {
  const langs = profile.languages?.join(", ") || "this project";
  const frameworks = profile.frameworks?.join(", ");

  let md = `# Copilot Instructions\n\n`;
  md += `## Project Context\n\n`;
  md += `This is a ${profile.architecture || "monolith"} project using ${langs}${frameworks ? ` with ${frameworks}` : ""}.\n\n`;

  md += `## Code Style\n\n`;
  md += `- Follow existing patterns in the codebase\n`;
  md += `- Use consistent naming conventions (Copilot infers these from existing code)\n`;
  md += `- Write clear, self-documenting code\n\n`;

  md += `## Testing\n\n`;
  md += `- Write tests for new features and bug fixes\n`;
  if (profile.build_commands?.test) {
    md += `- Run tests: \`${profile.build_commands.test}\`\n`;
  }
  md += `\n`;

  md += `## Safety\n\n`;
  md += `- Never modify files matching: ${(profile.protected_paths || [".env*"]).join(", ")}\n`;
  md += `- Never commit secrets or credentials\n`;
  md += `- Always verify changes compile/pass before committing\n\n`;

  md += `## When Unsure\n\n`;
  md += `- Check AGENTS.md for architecture guidance\n`;
  md += `- Look at existing similar code for patterns\n`;
  md += `- Ask the developer rather than guessing\n`;

  return md;
}

export function generateVscodeSettings() {
  const templatePath = join(TEMPLATES_DIR, "vscode-settings.json");
  if (existsSync(templatePath)) {
    return readFileSync(templatePath, "utf8");
  }
  // Fallback if template missing
  return JSON.stringify(
    {
      "chat.instructionsFilesLocations": {
        ".github/instructions/**/*.instructions.md": true,
      },
    },
    null,
    2
  ) + "\n";
}

// ─── Staging Orchestrator ───────────────────────────────────────────────────

/**
 * Write all planned artifacts to the staging directory.
 * @returns {{ written: string[], skipped: string[] }}
 */
export function stageArtifacts(target, artifacts, profile, scan) {
  const stagingDir = join(target, STAGING_DIR_NAME);
  const written = [];
  const skipped = [];

  for (const artifact of artifacts) {
    if (artifact.action === "skip") {
      skipped.push(artifact.label);
      continue;
    }

    const destPath = join(stagingDir, artifact.stagePath);

    // Ensure directory exists
    mkdirSync(dirname(destPath), { recursive: true });

    // Generate content based on artifact type
    switch (artifact.id) {
      case "repo-profile":
        writeFileSync(destPath, generateProfileYaml(profile), "utf8");
        break;

      case "agents-md":
        writeFileSync(destPath, generateAgentsMd(profile), "utf8");
        break;

      case "copilot-instructions":
        writeFileSync(destPath, generateInstructions(profile), "utf8");
        break;

      case "vscode-settings":
        writeFileSync(destPath, generateVscodeSettings(), "utf8");
        break;

      case "starter-skills":
        stageSkills(destPath);
        break;

      case "starter-agents":
        stageAgents(destPath);
        break;

      case "maintenance-skills":
        stageMaintenanceSkills(destPath);
        break;

      default:
        // Path-specific instruction templates
        if (artifact.templateSource) {
          stageInstructionTemplate(destPath, artifact.templateSource);
        }
        break;
    }

    written.push(artifact.label);
  }

  // Write manifest
  const manifest = buildManifest(artifacts, profile, scan);
  writeFileSync(
    join(stagingDir, MANIFEST_FILE),
    JSON.stringify(manifest, null, 2) + "\n",
    "utf8"
  );

  return { written, skipped };
}

function stageSkills(destDir) {
  if (!existsSync(SKILLS_DIR)) return;

  const skillDirs = readdirSync(SKILLS_DIR, { withFileTypes: true }).filter(
    (d) => d.isDirectory()
  );

  for (const dir of skillDirs) {
    const src = join(SKILLS_DIR, dir.name, "SKILL.md");
    if (existsSync(src)) {
      const dest = join(destDir, dir.name);
      mkdirSync(dest, { recursive: true });
      cpSync(src, join(dest, "SKILL.md"));
    }
  }
}

function stageInstructionTemplate(destPath, templateFile) {
  const src = join(INSTRUCTIONS_DIR, templateFile);
  if (existsSync(src)) {
    cpSync(src, destPath);
  }
}

function stageAgents(destDir) {
  if (!existsSync(AGENTS_DIR)) return;

  const agentFiles = readdirSync(AGENTS_DIR).filter((f) => f.endsWith(".yml"));

  for (const file of agentFiles) {
    const src = join(AGENTS_DIR, file);
    mkdirSync(destDir, { recursive: true });
    cpSync(src, join(destDir, file));
  }
}

function stageMaintenanceSkills(destDir) {
  if (!existsSync(META_SKILLS_DIR)) return;

  for (const skillName of MAINTENANCE_SKILLS) {
    const src = join(META_SKILLS_DIR, skillName, "SKILL.md");
    if (existsSync(src)) {
      const dest = join(destDir, skillName);
      mkdirSync(dest, { recursive: true });
      cpSync(src, join(dest, "SKILL.md"));
    }
  }
}

// ─── Apply (move staged → final) ───────────────────────────────────────────

/**
 * Read the staging manifest and apply files.
 * @returns {{ applied: string[], skipped: string[], errors: string[] }}
 */
export function applyStaged(target, force = false) {
  const stagingDir = join(target, STAGING_DIR_NAME);
  const manifestPath = join(stagingDir, MANIFEST_FILE);

  if (!existsSync(stagingDir)) {
    return { applied: [], skipped: [], errors: ["No ai-setup/ directory found. Run onboard first."] };
  }

  // Read manifest
  let manifest = null;
  if (existsSync(manifestPath)) {
    try {
      manifest = JSON.parse(readFileSync(manifestPath, "utf8"));
    } catch {}
  }

  if (!manifest) {
    return { applied: [], skipped: [], errors: ["No valid manifest found. Re-run onboard to regenerate."] };
  }

  const applied = [];
  const skipped = [];
  const errors = [];

  for (const artifact of manifest.artifacts) {
    const src = join(stagingDir, artifact.stagePath);
    const dest = join(target, artifact.targetPath);

    if (!existsSync(src)) {
      // For directory artifacts, check if directory exists
      if (artifact.id === "starter-skills") {
        const skillsSrc = join(stagingDir, ".github", "skills");
        if (existsSync(skillsSrc)) {
          const skillsDest = join(target, ".github", "skills");
          mkdirSync(skillsDest, { recursive: true });
          cpSync(skillsSrc, skillsDest, { recursive: true, force });
          applied.push(artifact.targetPath);
        }
      }
      continue;
    }

    if (existsSync(dest) && !force) {
      skipped.push(`${artifact.targetPath} (exists, use --force)`);
      continue;
    }

    try {
      mkdirSync(dirname(dest), { recursive: true });
      cpSync(src, dest);
      applied.push(artifact.targetPath);
    } catch (err) {
      errors.push(`${artifact.targetPath}: ${err.message}`);
    }
  }

  return { applied, skipped, errors };
}
