/**
 * Generation module — writes artifacts to the staging directory.
 */

import { dirname, join } from "node:path";
import { existsSync, mkdirSync, readFileSync, writeFileSync, readdirSync, copyFileSync, cpSync } from "node:fs";
import {
  AGENTS_DIR,
  INSTRUCTIONS_DIR,
  MAINTENANCE_SKILLS,
  MANIFEST_FILE,
  META_SKILLS_DIR,
  SKILLS_DIR,
  STAGING_DIR_NAME,
  TEMPLATES_DIR,
} from "./constants.js";
import { buildManifest } from "./templates.js";
import type { Artifact, Profile } from "./templates.js";
import type { ScanResult } from "./repo-detect.js";

// ─── YAML Formatter ─────────────────────────────────────────────────────────

export function formatYaml(obj: Record<string, unknown>, indent = 0): string {
  const pad = " ".repeat(indent);
  let out = "";

  for (const [key, value] of Object.entries(obj)) {
    if (value === null || value === undefined) continue;

    if (Array.isArray(value)) {
      if (value.length === 0) {
        out += `${pad}${key}: []\n`;
      } else if (typeof value[0] === "object") {
        out += `${pad}${key}:\n`;
        for (const item of value) {
          const lines = formatYaml(item as Record<string, unknown>, indent + 4)
            .split("\n")
            .filter(Boolean);
          out += `${pad}  - ${lines[0]!.trim()}\n`;
          for (const line of lines.slice(1)) {
            out += `${pad}    ${line.trim()}\n`;
          }
        }
      } else {
        out += `${pad}${key}:\n`;
        for (const item of value) {
          const s = String(item);
          out += `${pad}  - ${s.includes(" ") || s.includes("*") ? `"${s}"` : s}\n`;
        }
      }
    } else if (typeof value === "object") {
      out += `${pad}${key}:\n`;
      out += formatYaml(value as Record<string, unknown>, indent + 2);
    } else if (typeof value === "string" && (value.includes(" ") || value.includes("<"))) {
      out += `${pad}${key}: "${value}"\n`;
    } else {
      out += `${pad}${key}: ${value}\n`;
    }
  }

  return out;
}

// ─── File Generators ────────────────────────────────────────────────────────

export function generateProfileYaml(profile: Profile): string {
  return (
    `# Repository Profile\n` +
    `# yaml-language-server: $schema=https://raw.githubusercontent.com/eduardohilariodev/copilot-quickstart/main/schemas/repo-profile.schema.json\n` +
    `# Generated by copilot-quickstart v3.0.0\n` +
    `# Review and fill in <placeholders> before running meta-skills\n\n` +
    formatYaml(profile as unknown as Record<string, unknown>)
  );
}

export function generateAgentsMd(profile: Profile): string {
  const templatePath = join(TEMPLATES_DIR, "AGENTS.md");
  if (existsSync(templatePath)) {
    let content = readFileSync(templatePath, "utf8");
    const cmds = profile.build_commands || {};

    content = content
      .replace("{{repo_name}}", profile.name || "this-repo")
      .replace("{{project_description}}", `<!-- TODO: Add project description -->`)
      .replace("{{architecture_type}}", profile.architecture)
      .replace("{{languages}}", profile.languages?.join(", ") || "not specified")
      .replace("{{frameworks}}", profile.frameworks?.join(", ") || "none")
      .replace("{{directory_tree}}", `<!-- Run: tree -L 2 -I node_modules to fill -->`)
      .replace("{{cmd_install}}", cmds.install || "npm install")
      .replace("{{cmd_build}}", cmds.build || "npm run build")
      .replace("{{cmd_test}}", cmds.test || "npm test")
      .replace("{{cmd_lint}}", cmds.lint || "npm run lint")
      .replace("{{cmd_format}}", cmds.format || "npx prettier --write .")
      .replace("{{naming_conventions}}", buildNamingSection(profile))
      .replace("{{code_organization_rules}}", "- Follow existing patterns in the codebase\n- Use consistent naming (Copilot infers these from existing code)")
      .replace("{{error_handling_pattern}}", "- Follow existing error handling patterns\n- Add context to error messages")
      .replace("{{testing_strategy}}", cmds.test
        ? `- Run tests: \`${cmds.test}\`\n- Write tests for new features`
        : "- Write tests for new features and bug fixes")
      .replace("{{decision_1_title}}", "Decision 1")
      .replace("{{decision_1_rationale}}", "<!-- Document non-obvious architectural decisions here -->")
      .replace("{{decision_2_title}}", "Decision 2")
      .replace("{{decision_2_rationale}}", "<!-- Add more decisions as needed -->")
      .replace("{{protected_paths_list}}", (profile.protected_paths || [".env*"]).map((p) => `- \`${p}\``).join("\n"))
      .replace("{{runtime}}", detectRuntime(profile))
      .replace("{{package_manager}}", detectPackageManager(profile))
      .replace("{{ci_cd_platform}}", "<!-- Fill: GitHub Actions, GitLab CI, etc. -->");

    return content;
  }

  return generateAgentsMdFallback(profile);
}

function buildNamingSection(profile: Profile): string {
  if (!profile.naming) {
    return "- AI artifacts follow `kebab-case` naming\n- Skills: `verb-noun`\n- Agents: `role-scope`";
  }
  let section = "";
  section += profile.naming.skills_pattern === "verb-ing-domain"
    ? "- Skills: `verb-ing-domain` (e.g., `testing-code`, `managing-branches`)\n"
    : "- Skills: `domain-verb` (e.g., `code-testing`, `branch-managing`)\n";
  section += profile.naming.agents_pattern === "role-scope"
    ? "- Agents: `role-scope` (e.g., `coding-refactor`, `pr-code-review`)\n"
    : "- Agents: `domain-role` (e.g., `frontend-review`, `backend-coding`)\n";
  section += profile.naming.instructions_pattern === "topic"
    ? "- Instructions: `<topic>.instructions.md`"
    : "- Instructions: `<tech-domain-focus>.instructions.md`";
  return section;
}

function detectRuntime(profile: Profile): string {
  if (profile.languages?.includes("typescript") || profile.languages?.includes("javascript")) return "Node.js";
  if (profile.languages?.includes("python")) return "Python";
  if (profile.languages?.includes("go")) return "Go";
  if (profile.languages?.includes("rust")) return "Rust";
  if (profile.languages?.includes("java")) return "Java / JVM";
  return "<!-- Specify runtime -->";
}

function detectPackageManager(profile: Profile): string {
  const install = profile.build_commands?.install || "";
  if (install.includes("pnpm")) return "pnpm";
  if (install.includes("yarn")) return "yarn";
  if (install.includes("bun")) return "bun";
  if (install.includes("npm")) return "npm";
  if (install.includes("pip")) return "pip";
  if (install.includes("cargo")) return "cargo";
  return "<!-- Specify package manager -->";
}

function generateAgentsMdFallback(profile: Profile): string {
  const cmds = profile.build_commands || {};
  let md = `# AGENTS.md — ${profile.name}\n\n`;
  md += `## Quick Reference\n\n| Key | Value |\n|-----|-------|\n`;
  md += `| Languages | ${profile.languages?.join(", ") || "not specified"} |\n`;
  md += `| Frameworks | ${profile.frameworks?.join(", ") || "none"} |\n`;
  md += `| Architecture | ${profile.architecture || "monolith"} |\n`;
  md += `| Risk Level | ${profile.risk_level || "medium"} |\n\n`;
  md += `## Commands\n\n| Action | Command |\n|--------|--------|\n`;
  if (cmds.install) md += `| Install | \`${cmds.install}\` |\n`;
  if (cmds.build) md += `| Build | \`${cmds.build}\` |\n`;
  if (cmds.test) md += `| Test | \`${cmds.test}\` |\n`;
  if (cmds.lint) md += `| Lint | \`${cmds.lint}\` |\n`;
  md += `\n## Protected Paths\n\n`;
  md += (profile.protected_paths || [".env*"]).map((p) => `- \`${p}\``).join("\n");
  md += `\n\n## Agent Guidelines\n\n- Read this file before making changes\n- Run tests after every modification\n- Keep commits small and focused\n`;
  return md;
}

export function generateInstructions(profile: Profile): string {
  const templatePath = join(TEMPLATES_DIR, "copilot-instructions.md");
  if (existsSync(templatePath)) {
    let content = readFileSync(templatePath, "utf8");
    const langs = profile.languages?.join(", ") || "this project";
    const frameworks = profile.frameworks?.join(", ");

    content = content
      .replace("{{repo_name}}", profile.name || "this-repo")
      .replace("{{architecture_type}}", profile.architecture || "monolith")
      .replace("{{languages}}", langs)
      .replace("{{frameworks_clause}}", frameworks ? `with ${frameworks}` : "")
      .replace("{{code_style_rules}}", "- Follow existing patterns\n- Use consistent naming\n- Write clear code")
      .replace("{{testing_rules}}", profile.build_commands?.test
        ? `- Write tests for new features\n- Run tests: \`${profile.build_commands.test}\``
        : "- Write tests for new features")
      .replace("{{git_workflow_rules}}", "- Keep commits small and focused\n- Write descriptive commit messages")
      .replace("{{architecture_rules}}", "- Respect module boundaries\n- Ask before architectural changes")
      .replace("{{protected_paths}}", (profile.protected_paths || [".env*"]).join(", "))
      .replace("{{additional_security_rules}}", "")
      .replace("{{documentation_rules}}", "- Update docs when behavior changes");

    return content;
  }

  let md = `# Copilot Instructions\n\n## Project Context\n\n`;
  md += `This is a ${profile.architecture || "monolith"} project using ${profile.languages?.join(", ") || "this project"}.\n\n`;
  md += `## Safety\n\n- Never modify: ${(profile.protected_paths || [".env*"]).join(", ")}\n`;
  return md;
}

export function generateVscodeSettings(): string {
  const templatePath = join(TEMPLATES_DIR, "vscode-settings.json");
  if (existsSync(templatePath)) return readFileSync(templatePath, "utf8");
  return JSON.stringify({ "chat.instructionsFilesLocations": { ".github/instructions/**/*.instructions.md": true } }, null, 2) + "\n";
}

// ─── Staging ────────────────────────────────────────────────────────────────

export interface StageResult {
  written: string[];
  skipped: string[];
}

export function stageArtifacts(target: string, artifacts: Artifact[], profile: Profile, scan: ScanResult): StageResult {
  const stagingDir = join(target, STAGING_DIR_NAME);
  const written: string[] = [];
  const skipped: string[] = [];

  for (const artifact of artifacts) {
    if (artifact.action === "skip") { skipped.push(artifact.label); continue; }

    const destPath = join(stagingDir, artifact.stagePath);
    mkdirSync(dirname(destPath), { recursive: true });

    switch (artifact.id) {
      case "repo-profile": writeFileSync(destPath, generateProfileYaml(profile), "utf8"); break;
      case "agents-md": writeFileSync(destPath, generateAgentsMd(profile), "utf8"); break;
      case "copilot-instructions": writeFileSync(destPath, generateInstructions(profile), "utf8"); break;
      case "vscode-settings": writeFileSync(destPath, generateVscodeSettings(), "utf8"); break;
      case "starter-skills": stageSkills(destPath); break;
      case "starter-agents": stageAgents(destPath); break;
      case "maintenance-skills": stageMaintenanceSkills(destPath); break;
      default:
        if (artifact.templateSource) stageInstructionTemplate(destPath, artifact.templateSource);
        break;
    }
    written.push(artifact.label);
  }

  const manifest = buildManifest(artifacts, profile, scan);
  mkdirSync(stagingDir, { recursive: true });
  writeFileSync(join(stagingDir, MANIFEST_FILE), JSON.stringify(manifest, null, 2) + "\n", "utf8");

  return { written, skipped };
}

function stageSkills(destDir: string): void {
  if (!existsSync(SKILLS_DIR)) return;
  for (const entry of readdirSync(SKILLS_DIR, { withFileTypes: true })) {
    if (!entry.isDirectory()) continue;
    const src = join(SKILLS_DIR, entry.name, "SKILL.md");
    if (existsSync(src)) {
      const dest = join(destDir, entry.name);
      mkdirSync(dest, { recursive: true });
      copyFileSync(src, join(dest, "SKILL.md"));
    }
  }
}

function stageInstructionTemplate(destPath: string, templateFile: string): void {
  const src = join(INSTRUCTIONS_DIR, templateFile);
  if (existsSync(src)) copyFileSync(src, destPath);
}

function stageAgents(destDir: string): void {
  if (!existsSync(AGENTS_DIR)) return;
  for (const file of readdirSync(AGENTS_DIR).filter((f) => f.endsWith(".yml"))) {
    mkdirSync(destDir, { recursive: true });
    copyFileSync(join(AGENTS_DIR, file), join(destDir, file));
  }
}

function stageMaintenanceSkills(destDir: string): void {
  if (!existsSync(META_SKILLS_DIR)) return;
  for (const skillName of MAINTENANCE_SKILLS) {
    const src = join(META_SKILLS_DIR, skillName, "SKILL.md");
    if (existsSync(src)) {
      const dest = join(destDir, skillName);
      mkdirSync(dest, { recursive: true });
      copyFileSync(src, join(dest, "SKILL.md"));
    }
  }
}

// ─── Apply ──────────────────────────────────────────────────────────────────

export interface ApplyResult {
  applied: string[];
  skipped: string[];
  errors: string[];
}

export function applyStaged(target: string, force = false): ApplyResult {
  const stagingDir = join(target, STAGING_DIR_NAME);
  const manifestPath = join(stagingDir, MANIFEST_FILE);

  if (!existsSync(stagingDir)) {
    return { applied: [], skipped: [], errors: ["No ai-setup/ directory found. Run onboard first."] };
  }

  let manifest: { artifacts: Array<{ id: string; stagePath: string; targetPath: string }> } | null = null;
  if (existsSync(manifestPath)) {
    try { manifest = JSON.parse(readFileSync(manifestPath, "utf8")); } catch { /* ignore */ }
  }
  if (!manifest) {
    return { applied: [], skipped: [], errors: ["No valid manifest found. Re-run onboard to regenerate."] };
  }

  const applied: string[] = [];
  const skipped: string[] = [];
  const errors: string[] = [];

  for (const artifact of manifest.artifacts) {
    const src = join(stagingDir, artifact.stagePath);
    const dest = join(target, artifact.targetPath);

    if (!existsSync(src)) {
      if (artifact.id === "starter-skills" || artifact.id === "maintenance-skills") {
        const skillsSrc = join(stagingDir, ".github", "skills");
        if (existsSync(skillsSrc)) {
          const skillsDest = join(target, ".github", "skills");
          mkdirSync(skillsDest, { recursive: true });
          cpSync(skillsSrc, skillsDest, { recursive: true, force });
          applied.push(artifact.targetPath);
        }
      }
      continue;
    }

    if (existsSync(dest) && !force) { skipped.push(`${artifact.targetPath} (exists, use --force)`); continue; }

    try {
      mkdirSync(dirname(dest), { recursive: true });
      copyFileSync(src, dest);
      applied.push(artifact.targetPath);
    } catch (err) {
      errors.push(`${artifact.targetPath}: ${(err as Error).message}`);
    }
  }

  return { applied, skipped, errors };
}
